import { NextRequest } from "next/server";
import { err } from "@/lib/api-response";

/**
 * Demo data is generated by scripts/generate-demo-data.ts so it cannot mutate the
 * authenticated user's activity. This route remains as a guarded compatibility stub.
 */
export async function POST(req: NextRequest) {
  if (process.env.DEMO_DATA_ENABLED !== "true") {
    return err("Demo data endpoints are disabled; use the staging CLI generator", 404);
  }

  const configuredSecret = process.env.DEMO_ADMIN_SECRET;
  const suppliedSecret = req.headers.get("x-demo-admin-secret");
  if (!configuredSecret || !suppliedSecret || suppliedSecret !== configuredSecret) {
    return err("Demo admin authorization required", 403);
  }

  return err("Use `npm run demo:generate -- --run-id=<id>` from a staging environment", 501);
}
